version: '3.0'
networks:
  jenkins:
    driver: bridge

services:
  jenkins-blueocean:
    restart: on-failure
    image: jenkins-blueocean:latest
    networks:
      - jenkins
    environment:
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
     
    
    ports:
      - 10.165.162.8:8085:8080
      - 10.165.162.8:50000:50000
      - 10.165.162.8:80:80